version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./streamlytics.db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./streamlytics.db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
